### ISSUE TITLE
Soldering SOJ Hack

### ISSUE THREAD

**Issue by 122christo** [SukkoPera/OpenAmiga600RamExpansion#9]
Hello!
Soldering SOJ-Chips is not easy. So I made a hack: 
I soldered some Female PCB connector, like this one:
https://www.atd-shop.com/qx22B3-en/female-header-rm-127-mm-smt-single-row
on the PCB, bended the pins of the RAM-Chip into shape and put the pins in the
connector. Its like a socket, but much easier to solder. It works without Error.

**Comment by SukkoPera** [comment]
What you did is not very clear to me, can you please post a picture?

Anyway, even the "real" SOJ sockets are quite unreliable, they often fail after some time. I strongy recommend to solder the chips, it's not that hard if you have a good iron and good wire :).

**Comment by 122christo** [comment]
![SOJ-fem_header_02](https://github.com/SukkoPera/OpenAmiga600RamExpansion/assets/29799317/01b70124-6d19-4e6b-acd4-83ce11f8a369)

As you see on the Photo the hack works like a small DIP-Socket.
The Problem was my Amiga 600. I had to change the RAM, but the old PCB was  very  friable and I had to test some Chips. (Old NOS-chips) So this was my solution. 
The best is: You can very easily control the soldering quality and identify contact problems.

**Comment by SukkoPera** [comment]
That's a neat hack but it really doesn't look "solid" to me. I'm pretty sure it will cause problems in the future and it actually greatly increases the soldering time and effort.

You might be using solder wire that is too thick. 0.5 mm makes this kind of jobs much easier.

Anyway thanks for sharing!
